# Install Java 8
FROM amazoncorretto:8 AS build-stage

# from README.md

# Working directory
WORKDIR /usr/src/app

# Copy source code
COPY . .

# Build project
RUN ./mvnw package

# See https://whitfin.io/blog/speeding-up-maven-docker-builds/
FROM openjdk:8u171-jre-alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app /usr/src/app

CMD java -jar ./target/docker-example-1.1.3.jar

